name: Bug
description: Report a defect
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What is happening?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the behavior:
  - type: textarea
     attributes:
      label: Additional context (Add any other context about the problem here)
